{
   'name': "Market List",
   'version': "1.0",
   'description': 'Market List',
   'author': "Kimchhun Tan & Pisey Korn",
   'installable': True,
   'data': ['data/market_list_data.xml',
            'data/ir.model.access.csv',
            'view/market_list_request_view.xml',
            'view/market_list_request_pvk_view.xml',
            'view/market_list_request_general_view.xml',
            'view/purchase_order.xml',
            'view/market_list_request_general_view_a2a.xml',
            'view/supplier_configuration_view.xml',
            'data/market_list_sequence.xml',
            'reports/report.xml',
            'reports/request_form_report.xml',
            'reports/order_statistics.xml',
            'wizard/payment_report_wizard.xml',
            'wizard/payment_report_template.xml',
            'wizard/payment_report.xml',
            ],
   'depends': ['product','account']
}